#
# Copyright (C) 2011-2013 Barchart, Inc. <http://www.barchart.com/>
#
# All rights reserved. Licensed under the OSI BSD License.
#
# http://www.opensource.org/licenses/bsd-license.php
#

#
# All the values specified here will override the default values given
# in config.properties.
#
karaf.systemBundlesStartLevel=50

#
# You can place any customized configuration here.
#
#org.osgi.framework.system.packages.extra=
	
#
# http://fusesource.com/docs/esb/4.2/runtime/ESBRuntimeFailoverFileLock.html
#
karaf.lock.dir=${karaf.data}

#
# http://felix.apache.org/site/apache-felix-file-install.html
#
# monitor /etc by default; look for config and feature files
#
felix.fileinstall.dir    = ${karaf.base}/etc
felix.fileinstall.filter = .*(cfg|xml)
felix.fileinstall.poll   = 1000
felix.fileinstall.noInitialDelay = true
felix.fileinstall.log.level = 3
felix.fileinstall.enableConfigSave = false
felix.fileinstall.tmpdir  = ${karaf.data}/tmp/etc

#
# http://karaf.apache.org/manual/latest-2.2.x/developers-guide/branding-console.html
#
#org.osgi.framework.system.packages.extra = org.apache.karaf.branding; ${org.osgi.framework.system.packages.extra}

